server:
  port: 8082
spring:
  config:
    import: "optional:configserver:http://localhost:8085"
  application:
    name: HOTEL-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/microservices
    username: srthk
    password: hello
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
okta:
  oauth2:
    issuer: https://dev-80910482.okta.com/oauth2/default
    audience: api://default